### ISSUE TITLE
You do bash autocompletions totally wrong

### ISSUE THREAD

**Issue by ghost** [rwxrob/dot#64]
Here https://github.com/rwxrob/dot/blob/main/.bashrc#L346C1-L375C63
```bash
_have gh && . <(gh completion -s bash)
_have glow && . <(glow completion  bash)
_have pandoc && . <(pandoc --bash-completion)
# ... etc
```
Just wrong. They all sourced at the time. It is slow and not smart.

Bash completions can be lazy loaded only when they are needed.

0. Remove those ugly lines
1. Load bash_completion
```bash
test -f /usr/share/bash-completion/bash_completion && . $_
```
2. Generate completions for your tools
```
mkdir -p ~/.local/share/bash-completion/completions
gh completion -s bash > ~/.local/share/bash-completion/completions/gh
glow completion  bash > ~/.local/share/bash-completion/completions/glow
pandoc --bash-completion > ~/.local/share/bash-completion/completions/pandoc
... etc
```
3.  Open new terminal
4. Write `pandoc --<TAB>` or `gh <TAB>`
5. The completion will be loaded and used

**Comment by rwxrob** [comment]
Yeah, you totally and completely missed the point of this. If you don't understand why all that extra work isn't worth giving up having a single, transportable .bashrc I cannot help you.
